language: ruby
cache: bundler
rvm:
  - 2.3.0

before_script:
  - chmod +x ./script/* # or do this locally and commit
  - ./script/setup

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: 
  - ./script/cibuild

branches:
  only:
    - gh-pages

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
