title: "enzanki-ars"
description: "enzanki-ars's Website"
repository: enzanki-ars/enzanki-ars.github.io

remote_theme: enzanki-ars/enzanki-website-template

author:
  twitter: enzanki_ars

twitter:
  username: enzanki_ars

social:
  links:
    - https://twitter.com/enzanki_ars

timezone: America/New_York
encoding: utf-8

exclude: [vendor]

permalink: /:year/:month/:day/:title.html

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-remote-theme

